//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PListSerializer.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PListSerializer.Core.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///	&lt;dict&gt;
        ///		&lt;key&gt;text&lt;/key&gt;
        ///		&lt;string&gt;What does &apos;API&apos; stand for?&lt;/string&gt;
        ///		&lt;key&gt;question1&lt;/key&gt;
        ///		&lt;dict&gt;
        ///			&lt;key&gt;text&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///			&lt;key&gt;text2&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///			&lt;key&gt;text3&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///			&lt;key&gt;text4&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///		&lt;/dict&gt;
        ///	&lt;/dict&gt;
        ///&lt;/plist&gt;.
        /// </summary>
        internal static string PList1 {
            get {
                return ResourceManager.GetString("PList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;group_identifier&lt;/key&gt;
        ///	&lt;string&gt;Custom&lt;/string&gt;
        ///	&lt;key&gt;kMPPresetIdentifierKey&lt;/key&gt;
        ///	&lt;string&gt;Clarity Booster - 2018.lmp&lt;/string&gt;
        ///	&lt;key&gt;priority&lt;/key&gt;
        ///	&lt;integer&gt;0&lt;/integer&gt;
        ///	&lt;key&gt;Hidden&lt;/key&gt;
        ///	&lt;true/&gt;
        ///	&lt;key&gt;uuid&lt;/key&gt;
        ///	&lt;string&gt;259F230F-A18A-489C-87FE-024B503E1F5C&lt;/string&gt;
        ///	&lt;key&gt;AdjustmentLayers&lt;/key&gt;
        ///	&lt;array&gt;
        ///		&lt;dict&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plist2 {
            get {
                return ResourceManager.GetString("Plist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///  &lt;dict&gt;
        ///    &lt;key&gt;AdjustmentLayers&lt;/key&gt;
        ///    &lt;dict&gt;
        ///      &lt;key&gt;DevelopAdjustmentLayer&lt;/key&gt;
        ///      &lt;dict&gt;
        ///        &lt;key&gt;Sublayers&lt;/key&gt;
        ///        &lt;array&gt;
        ///          &lt;dict&gt;
        ///            &lt;key&gt;InfoImageName&lt;/key&gt;
        ///            &lt;string&gt;LensCorrection&lt;/string&gt;
        ///            &lt;key&gt;EffectsIMG&lt;/key&gt;
        ///            &lt;array&gt;
        ///              &lt;dict&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plist3 {
            get {
                return ResourceManager.GetString("Plist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///	&lt;dict&gt;
        ///		&lt;key&gt;text&lt;/key&gt;
        ///		&lt;string&gt;What does &apos;API&apos; stand for?&lt;/string&gt;
        ///		&lt;key&gt;question1&lt;/key&gt;
        ///		&lt;dict&gt;
        ///			&lt;key&gt;text&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///			&lt;key&gt;text2&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///			&lt;key&gt;text3&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///			&lt;key&gt;text4&lt;/key&gt;
        ///			&lt;string&gt;4242422&lt;/string&gt;
        ///		&lt;/dict&gt;
        ///	&lt;/dict&gt;
        ///&lt;/plist&gt;.
        /// </summary>
        internal static string PList4 {
            get {
                return ResourceManager.GetString("PList4", resourceCulture);
            }
        }
    }
}
